# 公共配置文件
# @author <a href="https://github.com/booboil">程序员booboil</a>
# @from <a href="https://yupi.icu">编程导航知识星球</a>
server:
  port: 8123
  servlet:
    context-path: /api
yuapi:
  client:
    access-key: yupi
    secret-key: abcdefgh